on:
  workflow_dispatch:
    inputs:
      env_dev:
        description: "Environment - Dev"
        type: boolean

      env_qa:
        description: "Environment - QA"
        type: boolean

      env_prod:
        description: "Environment - Prod"
        type: boolean

      region_us:
        description: "Region - US"
        type: boolean

      region_eu:
        description: "Region - EU"
        type: boolean
